export const squares = [
  'a8', 'b8', 'c8', 'd8', 'e8', 'f8', 'g8', 'h8',
  'a7', 'b7', 'c7', 'd7', 'e7', 'f7', 'g7', 'h7',
  'a6', 'b6', 'c6', 'd6', 'e6', 'f6', 'g6', 'h6',
  'a5', 'b5', 'c5', 'd5', 'e5', 'f5', 'g5', 'h5',
  'a4', 'b4', 'c4', 'd4', 'e4', 'f4', 'g4', 'h4',
  'a3', 'b3', 'c3', 'd3', 'e3', 'f3', 'g3', 'h3',
  'a2', 'b2', 'c2', 'd2', 'e2', 'f2', 'g2', 'h2',
  'a1', 'b1', 'c1', 'd1', 'e1', 'f1', 'g1', 'h1'
];

export const flippedSquares = [
  'h1', 'g1', 'f1', 'e1', 'd1', 'c1', 'b1', 'a1',
  'h2', 'g2', 'f2', 'e2', 'd2', 'c2', 'b2', 'a2',
  'h3', 'g3', 'f3', 'e3', 'd3', 'c3', 'b3', 'a3',
  'h4', 'g4', 'f4', 'e4', 'd4', 'c4', 'b4', 'a4',
  'h5', 'g5', 'f5', 'e5', 'd5', 'c5', 'b5', 'a5',
  'h6', 'g6', 'f6', 'e6', 'd6', 'c6', 'b6', 'a6',
  'h7', 'g7', 'f7', 'e7', 'd7', 'c7', 'b7', 'a7',
  'h8', 'g8', 'f8', 'e8', 'd8', 'c8', 'b8', 'a8'
];

export const squareColors = {
  'a8': 'white',
  'b8': 'black',
  'c8': 'white',
  'd8': 'black',
  'e8': 'white',
  'f8': 'black',
  'g8': 'white',
  'h8': 'black',
  'a7': 'black',
  'b7': 'white',
  'c7': 'black',
  'd7': 'white',
  'e7': 'black',
  'f7': 'white',
  'g7': 'black',
  'h7': 'white',
  'a6': 'white',
  'b6': 'black',
  'c6': 'white',
  'd6': 'black',
  'e6': 'white',
  'f6': 'black',
  'g6': 'white',
  'h6': 'black',
  'a5': 'black',
  'b5': 'white',
  'c5': 'black',
  'd5': 'white',
  'e5': 'black',
  'f5': 'white',
  'g5': 'black',
  'h5': 'white',
  'a4': 'white',
  'b4': 'black',
  'c4': 'white',
  'd4': 'black',
  'e4': 'white',
  'f4': 'black',
  'g4': 'white',
  'h4': 'black',
  'a3': 'black',
  'b3': 'white',
  'c3': 'black',
  'd3': 'white',
  'e3': 'black',
  'f3': 'white',
  'g3': 'black',
  'h3': 'white',
  'a2': 'white',
  'b2': 'black',
  'c2': 'white',
  'd2': 'black',
  'e2': 'white',
  'f2': 'black',
  'g2': 'white',
  'h2': 'black',
  'a1': 'black',
  'b1': 'white',
  'c1': 'black',
  'd1': 'white',
  'e1': 'black',
  'f1': 'white',
  'g1': 'black',
  'h1': 'white'
};
